Repository gordon-cs/gordon-360-api, pull requests merged in 2021-04, with the labels that each got.

#516 Apartapp include editor email in application data sent to frontend
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Services/HousingService.cs
Labels: ApartApps

#505 Apartapp - Debugging the save feature
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: ApartApps, ApartApps MVP, Bug

#519 Create ApartApps.md
  ApartApps.md
Labels: ApartApps MVP

#517 Added calculations for apartment points
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Services/HousingService.cs
Labels: 2 Points, ApartApps, ApartApps MVP

#530 database table diagram with attribute information and sample values
  ApartApps.md
Labels: ApartApps

#539 Apartapp develop refactoring
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Gordon360.csproj
  Gordon360/Models/AA_ApartmentApplications.cs
  Gordon360/Models/AA_ApartmentChoices.cs
  Gordon360/Models/AA_Applicants.cs
  Gordon360/Models/ACCOUNT.cs
  Gordon360/Models/CCT_DB_MODELS.Context.cs
  Gordon360/Models/CCT_DB_Models.Designer.cs
  Gordon360/Models/CCT_DB_Models.edmx
  Gordon360/Models/CCT_DB_Models.edmx.diagram
  Gordon360/Models/GET_AA_APARTMENT_CHOICES_BY_APP_ID_Result.cs
  Gordon360/Models/GET_AA_APPLICANTS_BY_APPID_Result.cs
  Gordon360/Models/GET_AA_APPLICANTS_DETAILS_Result.cs
  Gordon360/Models/GET_AA_APPLICATIONS_BY_ID_Result.cs
  Gordon360/Models/GET_AA_APPLICATIONS_Result.cs
  Gordon360/Models/GET_AA_CURRENT_APPLICATIONS_Result.cs
  Gordon360/Models/GET_SINGLE_MESSAGE_BY_ID_Result.cs
  Gordon360/Models/STUDENT_JOBS_PER_ID_NUM_Result.cs
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: ApartApps

#540 Added sorting of applicants to the load process
  Gordon360/Services/HousingService.cs
Labels: ApartApps, Bug

#524 ApartApp optimizations and implicit conversions
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Models/ViewModels/ApartmentChoiceViewModel.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: ApartApps, ApartApps MVP, Enhancement

#544 Apartapp develop - update after changes to Database tables
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Gordon360.csproj
  Gordon360/Models/AA_ApartmentApplications.cs
  Gordon360/Models/AA_ApartmentChoices.cs
  Gordon360/Models/AA_Applicants.cs
  Gordon360/Models/ACCOUNT.cs
  Gordon360/Models/CCT_DB_MODELS.Context.cs
  Gordon360/Models/CCT_DB_Models.Designer.cs
  Gordon360/Models/CCT_DB_Models.edmx
  Gordon360/Models/CCT_DB_Models.edmx.diagram
  Gordon360/Models/GET_AA_APARTMENT_CHOICES_BY_APP_ID_Result.cs
  Gordon360/Models/GET_AA_APPLICANTS_BY_APPID_Result.cs
  Gordon360/Models/GET_AA_APPLICANTS_DETAILS_Result.cs
  Gordon360/Models/GET_AA_APPLICATIONS_BY_ID_Result.cs
  Gordon360/Models/GET_AA_APPLICATIONS_Result.cs
  Gordon360/Models/GET_AA_CURRENT_APPLICATIONS_Result.cs
  Gordon360/Models/GET_SINGLE_MESSAGE_BY_ID_Result.cs
  Gordon360/Models/STUDENT_JOBS_PER_ID_NUM_Result.cs
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Models/ViewModels/ApartmentChoiceViewModel.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: ApartApps, ApartApps MVP

#557 Apartapp develop merge dev
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Gordon360.csproj
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Models/ViewModels/ApartmentChoiceViewModel.cs
  Gordon360/Models/ViewModels/ReturnGroupViewModel.cs
  Gordon360/Models/ViewModels/ReturnMessageViewModel.cs
  Gordon360/Models/ViewModels/ReturnRoomViewModel.cs
  Gordon360/Services/DirectMessageService.cs
  Gordon360/Services/HousingService.cs
  Tests/ApiEndpoints/test_gordon360_pytest.py
Labels: ApartApps

#555 Apartapp develop
  ApartApps.md
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/AuthorizationFilters/StateYourBusiness.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/ViewModels/ApartmentApplicantViewModel.cs
  Gordon360/Models/ViewModels/ApartmentApplicationViewModel.cs
  Gordon360/Models/ViewModels/ApartmentChoiceViewModel.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Static Classes/Names.cs
  README.md
  Tests/ApiEndpoints/test_allhousingapp_pytest.py
  Tests/ApiEndpoints/test_gordon360_pytest.py
Labels: ApartApps

#563 Apartapp develop
  Gordon360/AuthorizationFilters/StateYourBusiness.cs
  Gordon360/Gordon360.csproj
  Gordon360/Services/HousingService.cs
Labels: ApartApps

#559 Apartapp - update stateyourbusiness
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/AuthorizationFilters/StateYourBusiness.cs
Labels: ApartApps, ApartApps MVP

#562 Add ToLower in all other places where usernames are compared
  Gordon360/Services/HousingService.cs
Labels: ApartApps

#564 Urgent bug fix: Fixed the points to expect .Class to be a numeric char
  Gordon360/Services/HousingService.cs
Labels: ApartApps, ApartApps MVP, Bug

#566 Apartapp develop
  Gordon360/ApiControllers/HousingController.cs
  Gordon360/AuthorizationFilters/StateYourBusiness.cs
  Gordon360/Services/HousingService.cs
Labels: ApartApps
