Repository gordon-cs/gordon-360-api, pull requests merged in 2021-06, with the labels that each got.

#585 (S21) Add Image to Student News (API)
  Gordon360/ApiControllers/NewsController.cs
  Gordon360/ApiControllers/ProfilesController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Gordon360.csproj
  Gordon360/Models/CCT_DB_Models.Designer.cs
  Gordon360/Models/CCT_DB_Models.edmx.diagram
  Gordon360/Models/ChapelSummary.cs
  Gordon360/Models/MyGordon_DB_Models.Context.cs
  Gordon360/Models/MyGordon_DB_Models.Designer.cs
  Gordon360/Models/MyGordon_DB_Models.edmx
  Gordon360/Models/MyGordon_DB_Models.edmx.diagram
  Gordon360/Models/StudentNews.cs
  Gordon360/Models/ViewModels/StudentNewsViewModel.cs
  Gordon360/Services/NewsService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Utils/ImageUtils.cs
  Gordon360/Utils/UtilsInterfaces.cs
  Gordon360/Web.config
Labels: Feature, News

#606 Fixed: Some Alumni are not showed up on Advanced People Search
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Static Classes/Names.cs
Labels: Bug

#608 S21 Final Update: Advanced People Search Checkboxes
  Gordon360/ApiControllers/AccountsController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/RoleCheckingService.cs
  Gordon360/Startup.cs
  Gordon360/Static Classes/Data.cs
  Gordon360/Static Classes/Names.cs
Labels: 2 Points, Feature, Profile Page
