Repository gordon-cs/gordon-360-api, pull requests merged in 2022-09, with the labels that each got.

#709 Allow users to view their own memberships
  Gordon360/Controllers/MembershipsController.cs
Labels: Bug

#707 Fix faculty course schedules
  Gordon360/Services/ScheduleService.cs
Labels: Bug

#711 Add route for clifton strengths upload
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/CliftonStrengthsController.cs
  Gordon360/Models/ViewModels/CliftonStrengthsUploadResultViewModel.cs
  Gordon360/Properties/launchSettings.json
  Gordon360/Static Classes/Names.cs
Labels: Feature

#712 Perform quick search in parallel, centralize search logic, and misc search cleanup
  Gordon360/Controllers/AccountsController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/ViewModels/BasicInfoViewModel.cs
  Gordon360/Services/AccountService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: Enhancement, Code Quality, Search
