Repository gordon-cs/gordon-360-api, pull requests merged in 2023-06, with the labels that each got.

#903 [Rec-IM] Custom Participant Cleanup
  Gordon360/Controllers/AccountsController.cs
  Gordon360/Controllers/RecIM/ParticipantsController.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/RecIM/CustomParticipant.cs
  Gordon360/Models/CCT/RecIM/Participant.cs
  Gordon360/Models/ViewModels/RecIM/CustomParticipantPatchViewModel.cs
  Gordon360/Models/ViewModels/RecIM/CustomParticipantViewModel.cs
  Gordon360/Services/AccountService.cs
  Gordon360/Services/RecIM/MatchService.cs
  Gordon360/Services/RecIM/ParticipantService.cs
  Gordon360/Services/RecIM/TeamService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Static Classes/Names.cs
Labels: Code Quality, Rec-IM

#917 implement changes to update office locations for fac/staff
  Gordon360/Controllers/ProfilesController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/ViewModels/OfficeLocationPatchViewModel.cs
  Gordon360/Models/webSQL/Context/efpt.webSQL.config.json
  Gordon360/Models/webSQL/Context/webSQLContext.cs
  Gordon360/Models/webSQL/Models/GlobalSetting.cs
  Gordon360/Models/webSQL/Models/Mailstop.cs
  Gordon360/Models/webSQL/Models/Photo.cs
  Gordon360/Models/webSQL/Models/account.cs
  Gordon360/Models/webSQL/Models/account_profile.cs
  Gordon360/Program.cs
  Gordon360/Services/ProfileService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: s23

#918 Modify route for description
  Gordon360/Controllers/ScheduleControlController.cs
Labels: 1 Point, s23

#916 added a fromquery parameter to get schdules for a specific term
  Gordon360/Controllers/ScheduleController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/ScheduleService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: 3 Points, Search, s23

#913 Implement people search by graduate year
  Gordon360/Controllers/AccountsController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/AccountService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: s23

#931 Implementing people search by involvements
  Gordon360/Controllers/AccountsController.cs
  Gordon360/Controllers/AdvancedSearchController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/AccountService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: s23

#934 continue project from MyProfile-Involvments-Clutter - resolved merge conflicts
  Gordon360/Controllers/MembershipsController.cs
  Gordon360/Documentation/Gordon360.xml
Labels: s23
