Repository gordon-cs/gordon-360-api, pull requests merged in 2023-07, with the labels that each got.

#941 Modify code on api after increasing max length for description on the database
  Gordon360/Models/CCT/Context/CCTContextProcedures.cs
  Gordon360/Models/CCT/dbo/Schedule_Control.cs
Labels: 1 Point, s23

#953 changed patch to put in both routes
  Gordon360/Controllers/ProfilesController.cs
  Gordon360/Documentation/Gordon360.xml
Labels: s23

#955 S23 more security checks get memberships
  Gordon360/Controllers/MembershipsController.cs
  Gordon360/Documentation/Gordon360.xml
Labels: 1 Point, s23

#951 added a check for when you are asking from your profile, or your public profile
  Gordon360/Controllers/MembershipsController.cs
  Gordon360/Documentation/Gordon360.xml
Labels: 1 Point, s23

#969 Update model string size
  Gordon360/Models/webSQL/Models/account_profile.cs
Labels: s23

#974 changed mailstops route and removed duplicated import
  Gordon360/Controllers/ProfilesController.cs
  Gordon360/Services/ProfileService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: s23

#977 Create new route for getting all sessions and schedules
  Gordon360/Controllers/ScheduleController.cs
  Gordon360/Models/ViewModels/SessionCoursesViewModel.cs
  Gordon360/Services/ScheduleService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: 2 Points, s23

#979 [Rec-IM] Reduce match query for ladder matches
  Gordon360/Services/RecIM/MatchService.cs
Labels: Rec-IM, s23

#944 allow student to update graduation year on 360
  Gordon360/Controllers/ProfilesController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/CCT/dbo/CUSTOM_PROFILE.cs
  Gordon360/Models/CCT/dbo/FacStaff.cs
  Gordon360/Models/CCT/dbo/Student.cs
  Gordon360/Models/ViewModels/ProfileCustomViewModel.cs
  Gordon360/Models/ViewModels/ProfileViewModel.cs
  Gordon360/Models/ViewModels/PublicStudentProfileViewModel.cs
  Gordon360/Models/ViewModels/StudentProfileViewModel.cs
  Gordon360/Services/ProfileService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: s23

#982 [Rec-IM] 07202023 new routes
  Gordon360/Controllers/RecIM/SeriesController.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/RecIM/Activity.cs
  Gordon360/Models/CCT/RecIM/AffiliationPoints.cs
  Gordon360/Models/CCT/RecIM/Affiliations.cs
  Gordon360/Models/CCT/RecIM/Participant.cs
  Gordon360/Models/CCT/RecIM/SeriesTeam.cs
  Gordon360/Models/CCT/RecIM/SuperAdmin.cs
  Gordon360/Models/CCT/RecIM/Team.cs
  Gordon360/Models/ViewModels/RecIM/SeriesAutoSchedulerEstimateViewModel.cs
  Gordon360/Models/ViewModels/RecIM/TeamRecordPatchViewModel.cs
  Gordon360/Services/RecIM/SeriesService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: Rec-IM, s23

#971 Add new security group for the RecIM Director
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Static Classes/Names.cs
Labels: Rec-IM, s23

#964 Advisor, Leader, and members should be able to see members form the same club session
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/MembershipsController.cs
  Gordon360/Services/MembershipService.cs
Labels: Bug, s23

#981 S23/modify term selector
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/dbo/UserCourses.cs
  Gordon360/Models/ViewModels/SessionCoursesViewModel.cs
  Gordon360/Models/ViewModels/UserCoursesViewModel.cs
  Gordon360/Services/ScheduleService.cs
Labels: 1 Point, s23

#957 Add efpt instructions
  docs/Database.md
Labels: 1 Point, s23

#975 [Rec-IM] Release branch
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/AccountsController.cs
  Gordon360/Controllers/RecIM/ActivitiesController.cs
  Gordon360/Controllers/RecIM/MatchesController.cs
  Gordon360/Controllers/RecIM/ParticipantsController.cs
  Gordon360/Controllers/RecIM/RecIMController.cs
  Gordon360/Controllers/RecIM/SeriesController.cs
  Gordon360/Controllers/RecIM/SportsController.cs
  Gordon360/Controllers/RecIM/TeamsController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/RecIM/CustomParticipant.cs
  Gordon360/Models/CCT/RecIM/Match.cs
  Gordon360/Models/CCT/RecIM/MatchBracket.cs
  Gordon360/Models/CCT/RecIM/Participant.cs
  Gordon360/Models/CCT/RecIM/ParticipantView.cs
  Gordon360/Models/CCT/dbo/Housing_HallChoices.cs
  Gordon360/Models/ViewModels/RecIM/ActivityPatchViewModel.cs
  Gordon360/Models/ViewModels/RecIM/CustomParticipantPatchViewModel.cs
  Gordon360/Models/ViewModels/RecIM/CustomParticipantViewModel.cs
  Gordon360/Models/ViewModels/RecIM/LogoPatchViewModel.cs
  Gordon360/Models/ViewModels/RecIM/MatchBracketViewModel.cs
  Gordon360/Models/ViewModels/RecIM/ParticipantExtendedViewModel.cs
  Gordon360/Models/ViewModels/RecIM/ReportViewModel.cs
  Gordon360/Models/ViewModels/RecIM/Scheduler.cs
  Gordon360/Models/ViewModels/RecIM/SeriesScheduleExtendedViewModel.cs
  Gordon360/Models/ViewModels/RecIM/SportPatchViewModel.cs
  Gordon360/Models/ViewModels/RecIM/TeamPatchViewModel.cs
  Gordon360/Models/ViewModels/RecIM/TeamRecordViewModel.cs
  Gordon360/Program.cs
  Gordon360/Services/AccountService.cs
  Gordon360/Services/RecIM/ActivityService.cs
  Gordon360/Services/RecIM/MatchService.cs
  Gordon360/Services/RecIM/ParticipantService.cs
  Gordon360/Services/RecIM/RecIMService.cs
  Gordon360/Services/RecIM/SeriesService.cs
  Gordon360/Services/RecIM/SportService.cs
  Gordon360/Services/RecIM/TeamService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Static Classes/Names.cs
Labels: Release, Rec-IM, s23

#991 Recim halls part 2
  Gordon360/Controllers/RecIM/AffiliationsController.cs
  Gordon360/Controllers/RecIM/SeriesController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/ViewModels/RecIM/AffiliationPointsUploadViewModel.cs
  Gordon360/Models/ViewModels/RecIM/AffiliationPointsViewModel.cs
  Gordon360/Models/ViewModels/RecIM/SeriesUploadViewModel.cs
  Gordon360/Models/ViewModels/RecIM/TeamUploadViewModel.cs
  Gordon360/Services/RecIM/AffiliationService.cs
  Gordon360/Services/RecIM/SeriesService.cs
  Gordon360/Services/RecIM/TeamService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: Rec-IM
