Repository gordon-cs/gordon-360-api, pull requests merged in 2024-12, with the labels that each got.

#1104 Admin Actions in all Routes + DB Update: added Public Admin Actions
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/CCT/LostAndFound/ActionsTaken.cs
  Gordon360/Models/ViewModels/ActionsTakenViewModel.cs
  Gordon360/Models/ViewModels/MissingItemReportViewModel.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1106 Lost and Found Testing Environment
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/LostAndFound/ActionsTaken.cs
  Gordon360/Models/CCT/LostAndFound/GuestUsers.cs
  Gordon360/Models/CCT/LostAndFound/MissingItemData.cs
  Gordon360/Models/CCT/LostAndFound/MissingReports.cs
  Gordon360/Models/ViewModels/ActionsTakenViewModel.cs
  Gordon360/Models/ViewModels/MissingItemReportViewModel.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Services/ServicesExtensions.cs
  Gordon360/Static Classes/Names.cs
Labels: LostAndFoundProject24-25

#1109 Added API to check RA Pref Contact Method
  Gordon360/Controllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/ViewModels/Housing/RA_StudentsViewModel.cs
  Gordon360/Properties/launchSettings.json
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: WheresMyRAProject24-25

#1112 Added StateYourBusiness for API route protecting. Added new auth gr…
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/HousingController.cs
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Static Classes/Names.cs
Labels: WheresMyRAProject24-25

#1113 API to determine if a student is residential. This will be used to de…
  Gordon360/Controllers/HousingController.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/Housing/ResidentialStatus_View.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: WheresMyRAProject24-25

#1114 Merge WMRA API changes to SP
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/HousingController.cs
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/Housing/ResidentialStatus_View.cs
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Static Classes/Names.cs
Labels: WheresMyRAProject24-25

#1111 Updates from Code Review
  Gordon360/Authorization/AuthUtils.cs
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/CCTContextOverrides.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/LostAndFound/ActionsTakenData.cs
  Gordon360/Models/ViewModels/ActionsTakenViewModel.cs
  Gordon360/Models/ViewModels/MissingItemReportViewModel.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1116 Update Route URIs (to be more RESTful) + Auth Improvements + Doc Comments
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1117 HOTFIX General User Missing Items GET
  Gordon360/Services/LostAndFoundService.cs
Labels: Broken Feature, LostAndFoundProject24-25

#1118 Lost and Found API 1.0 Release
  Gordon360/Authorization/AuthUtils.cs
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/CCTContextOverrides.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/LostAndFound/ActionsTaken.cs
  Gordon360/Models/CCT/LostAndFound/ActionsTakenData.cs
  Gordon360/Models/CCT/LostAndFound/GuestUsers.cs
  Gordon360/Models/CCT/LostAndFound/MissingItemData.cs
  Gordon360/Models/CCT/LostAndFound/MissingReports.cs
  Gordon360/Models/ViewModels/ActionsTakenViewModel.cs
  Gordon360/Models/ViewModels/MissingItemReportViewModel.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Services/ServicesExtensions.cs
  Gordon360/Static Classes/Names.cs
Labels: Release, LostAndFoundProject24-25

#1119 Wmr merge api fixes
  Gordon360/Controllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/Housing/Current_On_Call.cs
  Gordon360/Models/CCT/Housing/Hall_Assignment_Ranges.cs
  Gordon360/Models/CCT/Housing/Hall_Tasks.cs
  Gordon360/Models/CCT/Housing/RA_Assigned_Ranges.cs
  Gordon360/Models/CCT/Housing/RA_Assigned_Ranges_View.cs
  Gordon360/Models/CCT/Housing/RA_On_Call.cs
  Gordon360/Models/CCT/Housing/ResidentialStatus_View.cs
  Gordon360/Models/ViewModels/Housing/HallAssignmentRangeViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_Assigned_RangesViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_ContactPreferenceViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_On_Call_GetViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_Status_ScheduleViewModel.cs
  Gordon360/Properties/launchSettings.json
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: WheresMyRAProject24-25

#1120 Wheres my RA release
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Enums/AuthGroup.cs
  Gordon360/Gordon360.csproj
  Gordon360/Models/CCT/Context/CCTContext.cs
  Gordon360/Models/CCT/Context/efpt.CCT.config.json
  Gordon360/Models/CCT/Housing/Current_On_Call.cs
  Gordon360/Models/CCT/Housing/Hall_Assignment_Ranges.cs
  Gordon360/Models/CCT/Housing/Hall_Task_Recurrence.cs
  Gordon360/Models/CCT/Housing/Hall_Tasks.cs
  Gordon360/Models/CCT/Housing/Halls.cs
  Gordon360/Models/CCT/Housing/RA_Assigned_Ranges_View.cs
  Gordon360/Models/CCT/Housing/RA_On_Call.cs
  Gordon360/Models/CCT/Housing/RA_Pref_Contact.cs
  Gordon360/Models/CCT/Housing/RA_Status.cs
  Gordon360/Models/CCT/Housing/RA_Status_Schedule.cs
  Gordon360/Models/CCT/Housing/RA_Students.cs
  Gordon360/Models/CCT/Housing/RD_Info.cs
  Gordon360/Models/CCT/Housing/Recurrence.cs
  Gordon360/Models/CCT/Housing/ResidentialStatus_View.cs
  Gordon360/Models/ViewModels/Housing/HallAssignmentRangeViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_Assigned_RangesViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_AssignmentViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_ContactPreferenceViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_On_CallViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_On_Call_GetViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_Status_ScheduleViewModel.cs
  Gordon360/Models/ViewModels/Housing/RA_StudentsViewModel.cs
  Gordon360/Models/ViewModels/Housing/RD_StudentsViewModel.cs
  Gordon360/Properties/launchSettings.json
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
  Gordon360/Static Classes/Names.cs
Labels: WheresMyRAProject24-25
