Repository gordon-cs/gordon-360-api, pull requests merged in 2025-02, with the labels that each got.

#1140 Fix Report Order
  Gordon360/Services/LostAndFoundService.cs
Labels: LostAndFoundProject24-25

#1149 Get FoundItem Route
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1150 Fixes from Review
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1144 Lost and Found Release 1.1
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: Release, LostAndFoundProject24-25

#1143 PUT Requests for Found Items
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/ViewModels/FoundItemViewModel.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1145 Get All Found Items With Their Actions
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Models/CCT/Context/CCTContextOverrides.cs
  Gordon360/Models/ViewModels/FoundItemViewModel.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1151 Fix events cache by increasing timeout
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/EventCacheRefreshService.cs
  Gordon360/Services/EventService.cs
  Gordon360/appsettings.json
Labels: Bug

#1147 RA Current Halls
  Gordon360/Authorization/StateYourBusiness.cs
  Gordon360/Controllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: WheresMyRAProject24-25

#1142 Added RAs to permissions that allow them to see all on call RAs
  Gordon360/Authorization/StateYourBusiness.cs
Labels: WheresMyRAProject24-25

#1154 Updated GET route to include date filtering
  Gordon360/Controllers/LostAndFoundController.cs
  Gordon360/Services/LostAndFoundService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: LostAndFoundProject24-25

#1141 Update Delete task API to be a logical delete so that we can preserve…
  Gordon360/Controllers/HousingController.cs
  Gordon360/Documentation/Gordon360.xml
  Gordon360/Properties/launchSettings.json
  Gordon360/Services/HousingService.cs
  Gordon360/Services/ServiceInterfaces.cs
Labels: WheresMyRAProject24-25
